PM5 update
Muqsit/ArenaGenerator pull request #2
Opened 2023-06-20 06:51 UTC by NopeNotDark

2023-06-20 06:51 UTC, NopeNotDark commented
Needs testing.

2023-06-24 04:20 UTC, Muqsit requested changes

2023-06-24 04:20 UTC, Muqsit commented on src/muqsit/arenagenerator/ArenaAllocator.php
> +    public static function optimized(): self {
The code needs to match the original format (indentation, brackets, etc.).

2023-06-24 04:20 UTC, Muqsit commented on src/muqsit/arenagenerator/layout/chunk/PreloadedChunk.php
> +	public function __construct(array $sub_chunks, array $tiles, array $height_map, ?bool $light_populated){
Existing entities must be transferred onto copied arenas (this change will prevent stuff like zombies in a region or hung paintings to be lost during copying).

2023-06-24 04:20 UTC, Muqsit commented on src/muqsit/arenagenerator/layout/chunk/PreloadedChunk.php
> +			$tile = $tile_factory->createFromData($world, $data->getCleanedNBT());
`Tile::getSaveNbt()` would give the complete NBT to restore tiles to their exact state.

2023-06-28 10:13 UTC, closed without merging